### ISSUE TITLE
Docker container update

### ISSUE THREAD

**Issue by scrasmussen** [NCAR/ccpp-scm#455]
From @ligiabernardet 
> Mike will take a look.
> Not sure where/how the container is built and stored, but should be able to get access.

For past releases, Grant built docker image on windows machine and images stored on dockerhub.
Is DTC still hosting use of dockerhub?
Grant pass any info to Mike for reproducing.

Mike looked at current docker build - it won't even build as it is outdated
Sam suggests building docker with debian.

**Comment by mkavulich** [comment]
Update on latest progress: there's actually a problem creating the existing CCPP v6 container on certain machines, seems to be related to having a very old version of git (1.8.3); this is mainly due to being based on CentOS 7 which is near end-of-life. I will look into updating the Common Docker container to use CentOS 8.
